---
title: "Bar Chart Race - States With the Highest Public School Enrollment"
author: ''
date: '2020-04-16'
categories: animation
tags:
- animation
- dataviz
- ggplot2
- gganimate
- R
- NCES
- barchartrace
subtitle: 'Animation created using ggplot2 and animation packages for social media distribution'
description: 'Since 1870, states’ populations and public school enrollment have increased, with differential growth across the country.'
bigimg: [{src: "/img/barChartRaceState.png", desc: "Since 1870, states’ populations and public school enrollment have increased, with differential growth across the country."}]
---

```{r setup knitr, echo = FALSE, warning = FALSE}
library(knitr)
# knitr::opts_chunk$set(cache = TRUE, warning = FALSE, message = FALSE, dpi = 180, out.extra='class = "img-responsive"')

```

Linked here: [https://nces.ed.gov/blogs/nces/post/racing-bar-chart](https://nces.ed.gov/blogs/nces/post/racing-bar-chart)

```{r setup, echo = F}
knit_hooks$set(wrap = function(before, options, envir){
  if (before){
    paste0('<', options$wrap, '>')
  } else {
    paste0('</', options$wrap, '>')
  }
})

knitr::opts_chunk$set(warning = FALSE, message = FALSE, dpi = 180, fig.height = 5, fig.width = 7, fig.align = "center")
options(width=140, dplyr.width = 150)
```
  
 ***
  
## Full image:
  
<iframe width="1600" height="900" src="https://www.youtube.com/embed/aOVBVSordsQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
 ***
 
Interested in learning more? Hire me to consult on your next project, follow me on [twitter](https://twitter.com/mikeleeco), leave a comment, or contact me via [email](mailto:mdlee12@gmail.com). All inquiries welcome!
  